insert into usr (first_name, middle_name, last_name, email) values
('Иван', 'Иванович', 'Иванов', 'ivanov@my.example.com'),
('Петр', 'Петрович', 'Петров', 'petrov@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov@my.example.com'),
('Иван', 'Иванович', 'Иванов', 'ivanov1@my.example.com'),
('Петр', 'Петрович', 'Петров', 'petrov1@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov1@my.example.com'),
('Иван', 'Иванович', 'Иванов', 'ivanov2@my.example.com'),
('Петр', 'Петрович', 'Петров', 'petrov2@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov2@my.example.com'),
('Петр', 'Петрович', 'Петров', 'petrov3@my.example.com'),
('Петр', 'Петрович', 'Петров', 'petrov4@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov3@my.example.com'),
('Иван', 'Иванович', 'Иванов', 'ivanov3@my.example.com'),
('Петр', 'Петрович', 'Петров', 'petrov5@my.example.com'),
('Гена', 'Иванович', 'Саров', 'sarov@my.example.com'),
('Андрей', 'Петрович', 'Перек', 'perek@my.example.com'),
('Гоша', 'Петрович', 'Рудковский', 'rudik@my.example.com'),
('Саша', 'Иванович', 'Варивада', 'varida@my.example.com'),
('Паша', 'Петрович', 'Журавлев', 'pashka@my.example.com'),
('Ваня', 'Петрович', 'Радковский', 'radkodv@my.example.com'),
('Игорь', 'Иванович', 'Мазур', 'mazur@my.example.com'),
('Кеша', 'Петрович', 'Зорин', 'zorin@my.example.com'),
('Люда', 'Петрович', 'Никонова', 'nikonova@my.example.com'),
('Максим', 'Петрович', 'Щипко', 'maximka@my.example.com');
insert into usr (first_name, middle_name, last_name, e_mail, phone, birth_date, role_name) values
('Надя', 'Ивановна', 'Залицина', 'zal@my.example.com', '+7(978)855-31-00', '2005-03-15', 'user'),
('Александр', 'Андреевич', 'Земин', 'zel@my.example.com', '+7(978)855-31-01', '2005-03-15', 'user'),
('Андрей', 'Максимович', 'Розин', 'roz@my.example.com', '+7(978)855-31-02', '2005-03-15', 'user'),
('Милана', 'Романовна', 'Пурина', 'puri@my.example.com', '+7(978)855-31-03', '2005-03-15', 'user'),
('Елена', 'Александровна', 'Лерина', 'lirinn@my.example.com', '+7(978)855-31-04', '2005-03-15', 'user'),
('Юлия', 'Юрьевна', 'Фадина', 'fadina@my.example.com', '+7(978)855-31-05', '2005-03-15', 'user'),
('Алекс', 'Иванович', 'Кондра', 'kondr@my.example.com', '+7(978)855-31-06', '2005-03-15', 'user'),
('Данил', 'Иванович', 'Дёмин', 'demin@my.example.com', '+7(978)855-31-07', '2005-03-15', 'user'),
('Иван', 'Степанович', 'Закин', 'zakin@my.example.com', '+7(978)855-31-08', '2005-03-15', 'user'),
('Костя', 'Георгевич', 'Лупин', 'lupin@my.example.com', '+7(978)855-31-09', '2005-03-15', 'user');